### ISSUE TITLE
Cannot run with google colab

### ISSUE THREAD

**Issue by cosineDaDa0623** [ATOMScience-org/AMPL#229]
Hi! I am currently learning and plan to use AMPL in the future. However, I encountered some issues when run the tutorials codes in colab. Many packages cannot be downloaded correctly maybe due to the python version. However, when I changed the Python version the problem still exists.  Hope you can help me with the issues.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _dep_map(self)
   3107         try:
-> 3108             return self.__dep_map
   3109         except AttributeError:

15 frames
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _get(self, path)
   1724 
   1725     def _get(self, path):
-> 1726         with open(path, 'rb') as stream:
   1727             return stream.read()
   1728 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/scipy-1.10.1.dist-info/METADATA'
```
Xian.

**Comment by mauvais2** [comment]
Hi! @paulsonak helped on this. It's not Python 3.10 issue. The problem is from DeepChem 2.7.1. It actually un-pinned the requirement for scipy <1.9.  It was asked to push the updated branch (from end of March, 2023) to PyPi https://github.com/deepchem/deepchem/pull/3309. But it hasn't been pushed yet. The current DC 2.7.1 was from Dec, 2022.

The workaround is to add `! pip install scipy==1.10.1` after the pip install cell from the AMPL tutorials. For example:

> ! pip install rdkit-pypi
> ! pip install deepchem
> 
> import deepchem
> ! pip install umap
> ! pip install -U --ignore-installed numba
> ! pip install umap-learn
> ! pip install molvs
> ! pip install bravado
> ! pip install scipy==1.10.1                    <---  add the last line to install `scipy==1.10.1`

I tested with AMPL tutorial 02, 03, 04 and and `import atomsci.ddm.pipeline.diversity_plots as dp` work fine (after restarting a new runtime when switching to a new notebook). 

Let us know if this works for you. Thanks.
