### ISSUE TITLE
compare_models.get_filesystem_perf_results() retrieved metadata and performance metrics from deleted models

### ISSUE THREAD

**Issue by Hokiee** [ATOMScience-org/AMPL#252]
I used compare_models.get_filesystem_perf_results() of AMPL 1.6.0 to retrieve metadata and performance metrics for models stored in the filesystem from hyperparameter search runs.

`from atomsci.ddm.pipeline import compare_models as cm`
`pred_df = cm.get_filesystem_perf_results(odir, pred_type='regression')`

I found that this function retrieved metadata and performance metrics, including all the information except model_path, from the models I had deleted from the filesystem (odir). This is a sample output file, [pred_df.csv](https://github.com/ATOMScience-org/AMPL/files/13573627/pred_df.csv).

How can I prevent this function from retrieving information from deleted models? Thanks.

**Comment by mcloughlin2** [comment]
Hi Pinyi,

My guess is that you deleted the .tar.gz files for the models, but didn’t delete the corresponding model result directories that also get saved under the hyperparameter search directory. In addition to searching for model tarballs, the current implementation of get_filesystem_perf_results also walks down the directory tree rooted at ‘odir’ and retrieves the performance metrics and parameters from any directory that looks like a result directory (i.e., any directory that contains files named model_metadata.json and model_metrics.json). I believe there’s code to eliminate duplication between the tarball and result_dir copies of the same model.

The workaround for the problem you’re having is to move the .tar.gz files for the models you want to compare into a different directory, so that the model result dirs. don’t get searched.

Thanks, Kevin


From: Pinyi Lu ***@***.***>
Date: Tuesday, December 5, 2023 at 2:34 PM
To: ATOMScience-org/AMPL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ATOMScience-org/AMPL] compare_models.get_filesystem_perf_results() retrieved metadata and performance metrics from deleted models (Issue #252)

I used compare_models.get_filesystem_perf_results() of AMPL 1.6.0 to retrieve metadata and performance metrics for models stored in the filesystem from hyperparameter search runs.

from atomsci.ddm.pipeline import compare_models as cm
pred_df = cm.get_filesystem_perf_results(odir, pred_type='regression')

I found that this function retrieved metadata and performance metrics, including all the information except model_path, from the models I had deleted from the filesystem (odor). This is a sample output file, pred_df.csv<https://urldefense.us/v3/__https:/github.com/ATOMScience-org/AMPL/files/13573627/pred_df.csv__;!!G2kpM7uM-TzIFchu!2ozC-0uS1p7R0QhkHmuj-RcvNT4tzjx2tRJz9tYjGO-04A7HNnbdgpk-Zt3FmhIHPc2ieyAlUxWxnEfNjGi2r1fddAp7$>.

How can I prevent this function from retrieving information from deleted models? Thanks.

**Comment by Hokiee** [comment]
Thanks, Kevin.

The issue was resolved after deleting other model-related files in the result directory in addition to model tarballs. I'm to close this issue.
