### ISSUE TITLE
AD domain calculation does not work on a model shared from elsewhere

### ISSUE THREAD

**Issue by paulsonak** [ATOMScience-org/AMPL#89]
When running `atomsci.ddm.pipeline.predict_from_model()`, there is an option to calculate metrics around the applicability domain. However, this requires calculating the distance from the training data to the proposed molecules. In the case of a model shared from elsewhere, the [code](https://github.com/ATOMconsortium/AMPL/blob/master/atomsci/ddm/pipeline/model_pipeline.py#L845) will attempt to load the original training data from the original location (which would be a file system on a different computer). When it can't load the data, it throws an error and does not return any predictions (which works regardless of where the training data is). 
1. Quick fix: try/catch for original training data not located
2. Longer term fix: sharing models should include the original training data? And the code needs to be updated to find where that data is? That would involve sharing the split file + dataset + model. This might be useful anyway, unless the training data is proprietary.

**Comment by paulsonak** [comment]
Alternate: allow passage of training + split data from user.. more complicated/ confusing though.

**Comment by mcloughlin2** [comment]
We could certainly include the training data and split file in the model tarball, but that shouldn't be the default option since (1) pharma company users will definitely not want this, and (2) it will potentially make the tarball files much bigger. Since most models trained in a hyperparam search won't get shared, that would waste a lot of disk space. Maybe we can write a script to add the training dataset and split file to a specific model that a user wants to share and allow AD calculations for.

**Comment by paulsonak** [comment]
I added a try/except catch here: https://github.com/ATOMconsortium/AMPL/pull/91
